"""
plugins/elb - Elastic Load Balancing Analysis Tools

Includes all load balancer types: ALB, NLB, CLB, GWLB
"""

CATEGORY = {
    "name": "elb",
    "display_name": "ELB",
    "description": "Elastic Load Balancing (ALB/NLB/CLB/GWLB)",
    "description_en": "Elastic Load Balancing (ALB/NLB/CLB/GWLB)",
    "aliases": ["loadbalancer", "lb"],
    "sub_services": ["alb", "nlb", "clb", "gwlb"],
}

TOOLS = [
    {
        "name": "미사용 ELB",
        "name_en": "Unused ELB",
        "description": "타겟이 없는 로드밸런서 탐지 (ALB/NLB/CLB/GWLB 전체)",
        "description_en": "Detect load balancers without targets (all types)",
        "permission": "read",
        "module": "unused",
        "area": "unused",
    },
    {
        "name": "ALB 미사용 분석",
        "name_en": "Unused ALB Analysis",
        "description": "타겟이 없는 ALB 탐지",
        "description_en": "Detect ALBs without targets",
        "permission": "read",
        "module": "alb_unused",
        "area": "unused",
        "sub_service": "alb",
    },
    {
        "name": "NLB 미사용 분석",
        "name_en": "Unused NLB Analysis",
        "description": "타겟이 없는 NLB 탐지",
        "description_en": "Detect NLBs without targets",
        "permission": "read",
        "module": "nlb_unused",
        "area": "unused",
        "sub_service": "nlb",
    },
    {
        "name": "CLB 미사용 분석",
        "name_en": "Unused CLB Analysis",
        "description": "인스턴스가 없는 CLB 탐지",
        "description_en": "Detect CLBs without instances",
        "permission": "read",
        "module": "clb_unused",
        "area": "unused",
        "sub_service": "clb",
    },
    {
        "name": "Target Group 분석",
        "name_en": "Target Group Analysis",
        "description": "미연결/빈 타겟 그룹 탐지 (ALB/NLB)",
        "description_en": "Detect unattached/empty target groups (ALB/NLB)",
        "permission": "read",
        "module": "target_group_audit",
        "area": "cost",
    },
    {
        "name": "CLB Migration Advisor",
        "name_en": "CLB Migration Advisor",
        "description": "CLB→ALB/NLB 마이그레이션 분석 및 추천",
        "description_en": "CLB to ALB/NLB migration analysis",
        "permission": "read",
        "module": "migration_advisor",
        "area": "cost",
        "sub_service": "clb",
    },
    {
        "name": "ELB Security Audit",
        "name_en": "ELB Security Audit",
        "description": "SSL/TLS, WAF, 인증서, 액세스 로그 보안 감사",
        "description_en": "SSL/TLS, WAF, certificate, access log security audit",
        "permission": "read",
        "module": "security_audit",
        "area": "security",
    },
    {
        "name": "ALB Listener Rules 분석",
        "name_en": "ALB Listener Rules Analysis",
        "description": "ALB 리스너 규칙 복잡도 및 최적화 분석",
        "description_en": "ALB listener rule complexity and optimization",
        "permission": "read",
        "module": "listener_rules",
        "area": "audit",
        "sub_service": "alb",
    },
    {
        "name": "ALB 로그 분석",
        "name_en": "ALB Log Analysis",
        "description": "S3에 저장된 ALB 액세스 로그 분석",
        "description_en": "Analyze ALB access logs stored in S3",
        "permission": "read",
        "module": "alb_log",
        "area": "log",
        "single_region_only": True,
        "sub_service": "alb",
    },
]
