"""
core/types - 공통 타입 정의 패키지

TypedDict, Protocol, 타입 별칭을 제공합니다.

모듈 구조:
    - aliases.py: 타입 별칭 (AccountId, RegionName 등)
    - aws.py: AWS 클라이언트 Protocol 및 타입

Usage:
    # 타입 별칭 사용
    from core.types import AccountId, RegionName

    # AWS 클라이언트 타입 사용
    from core.types.aws import EC2Client, S3Client

    # 기존 타입 사용 (하위 호환성)
    from core.types import ToolMetadata, EC2Instance
"""

# 기존 types.py의 모든 내용 재export (하위 호환성)
# 새로운 타입 별칭
from core.types.aliases import (
    AccountId,
    AlarmName,
    Arn,
    BucketName,
    CidrBlock,
    CollectResult,
    DBClusterId,
    DBInstanceId,
    DimensionName,
    DimensionValue,
    FunctionName,
    GroupName,
    ImageId,
    InstanceId,
    InternetGatewayId,
    IpAddress,
    IsoTimestamp,
    JsonDict,
    JsonList,
    JsonValue,
    KeyId,
    LogGroupName,
    MetricName,
    NatGatewayId,
    NetworkInterfaceId,
    PolicyArn,
    ProfileName,
    RegionName,
    ResourceId,
    RoleName,
    RouteTableId,
    SecretId,
    SecurityGroupId,
    SnapshotId,
    SubnetId,
    TagKey,
    Tags,
    TagValue,
    UnixTimestamp,
    UserName,
    VolumeId,
    VpcId,
    is_valid_account_id,
    is_valid_arn,
    is_valid_region,
)

# AWS 클라이언트 타입
from core.types.aws import (
    AnyClient,
    AnyPaginator,
    AnySession,
    AWSResponse,
    AWSServiceName,
    BaseClientProtocol,
    Boto3Session,
    ClientFactory,
    PaginatedResponse,
    PaginatorProtocol,
    ResponseMetadata,
    SessionProtocol,
)
from core.types_legacy import (
    AnalysisResult,
    AWSClient,
    AWSConfig,
    AWSResource,
    AWSTag,
    CategoryMetadata,
    DescribeInstancesResponse,
    DescribeVolumesResponse,
    DiscoveredCategory,
    EBSVolume,
    EC2Instance,
    ErrorInfo,
    ListBucketsResponse,
    OptionsCollector,
    PluginRunner,
    RDSInstance,
    S3Bucket,
    SessionProvider,
    SSOConfig,
    ToolMetadata,
    is_tool_metadata,
)
from core.types_legacy import PaginatedResponse as LegacyPaginatedResponse

__all__ = [
    # Legacy 타입 (하위 호환성)
    "ToolMetadata",
    "CategoryMetadata",
    "DiscoveredCategory",
    "AWSTag",
    "AWSResource",
    "EC2Instance",
    "EBSVolume",
    "S3Bucket",
    "RDSInstance",
    "PluginRunner",
    "OptionsCollector",
    "AWSClient",
    "SessionProvider",
    "AnalysisResult",
    "ErrorInfo",
    "LegacyPaginatedResponse",
    "DescribeInstancesResponse",
    "DescribeVolumesResponse",
    "ListBucketsResponse",
    "AWSConfig",
    "SSOConfig",
    "is_tool_metadata",
    # 타입 별칭
    "AccountId",
    "RegionName",
    "ResourceId",
    "Arn",
    "RoleName",
    "ProfileName",
    "InstanceId",
    "VolumeId",
    "SnapshotId",
    "ImageId",
    "SecurityGroupId",
    "VpcId",
    "SubnetId",
    "RouteTableId",
    "InternetGatewayId",
    "NatGatewayId",
    "NetworkInterfaceId",
    "BucketName",
    "DBInstanceId",
    "DBClusterId",
    "FunctionName",
    "UserName",
    "GroupName",
    "PolicyArn",
    "LogGroupName",
    "MetricName",
    "AlarmName",
    "DimensionName",
    "DimensionValue",
    "KeyId",
    "SecretId",
    "JsonValue",
    "JsonDict",
    "JsonList",
    "Tags",
    "TagKey",
    "TagValue",
    "IsoTimestamp",
    "UnixTimestamp",
    "CidrBlock",
    "IpAddress",
    "CollectResult",
    # 유틸리티 함수
    "is_valid_account_id",
    "is_valid_region",
    "is_valid_arn",
    # AWS 타입
    "SessionProtocol",
    "BaseClientProtocol",
    "PaginatorProtocol",
    "ClientFactory",
    "AnyClient",
    "AnySession",
    "AnyPaginator",
    "Boto3Session",
    "AWSServiceName",
    "PaginatedResponse",
    "ResponseMetadata",
    "AWSResponse",
]
